# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Observatory
    weight: 10
    identifier: Home
  - name: About
    url: ""
    weight: 11
    parent: Home
  - name: News
    url: ""
    weight: 12
    parent: Home
  - name: Topics â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼
    url: ""
    weight: 13
    parent: Home
  - name: "Observatory Stakeholder Network"
    url: "/authors/admin/"
    weight: 15
    parent: Home
  - name: "Technical Forum"
    url: '/services/music-professionals/'
    weight: 16
    parent: Home
  - name: Open Music Europe ğŸ‡ªğŸ‡º 
    url: '/project/open-music-europe/'
    weight: 17
    parent: Home
  - name: "Reprex â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼"
    url: '/services/public-policy/'
    weight: 18
    parent: Home
  - name: Join
    url: "#join"
    weight: 20
    parent: Home
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: EU Open Data Portal
    url: '#pillars'
    weight: 41
    parent: Data
  - name: Europeana
    url: '#pillars'
    weight: 42
    parent: Data
  - name: Wikibase
    url: '#pillars'
    weight: 43
    parent: Data
  - name: Open Science Repository
    url: 'https://zenodo.org/communities/music_observatory'
    weight: 44
    parent: Data
  - name: ğŸ›ï¸ Music Economy
    url: '#pillars'
    weight: 45
    parent: Data
  - name: ğŸ›ï¸ Diversity & Circulation
    url: '#pillars'
    weight: 46
    parent: Data
  - name: ğŸ›ï¸ Music & Society
    url: '#pillars'
    weight: 47
    parent: Data
  - name: ğŸ›ï¸ Music Tech & Innovation
    url: '#pillars'
    weight: 48
    parent: Data
  - name: ğŸ› Sustainability
    weight: 49
    parent: Data
  - name: Services
    url: '#services'
    weight: 50
    identifier: Services
  - name: Applications
    url: 'apps/'
    weight: 51
    parent: Services
  - name: Open Music Software
    url: '#releases'
    weight: 52
    parent: Services
  - name: Code
    url: '/category/r-bloggers/'
    weight: 54
    parent: Services
  - name: Publications
    url: '#featured'
    weight: 70
    identifier: Publications
  - name: Featured
    url: '#featured'
    weight: 71
    parent: Publications
  - name: All Publications
    url: '#publications'
    weight: 72
    parent: Publications
  - name: Events
    url: '#contact'
    weight: 80
    identifier: Events
  - name: Public talks
    url: '#talks'
    weight: 82
    parent: Events
  - name: Contact
    url: '#contact'
    weight: 95
    identifier: Contact


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
