# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    weight: 10
    identifier: Home
  - name: News â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼
    url: ../post/
    weight: 12
    parent: Home
#  - name: Topics â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼
#    url: ""
#    weight: 13
#    parent: Home
  - name: "About"
    url: ../authors/admin/
    weight: 11
    parent: Home
  - name: "Observatory Stakeholder Network"
    url: ../authors/observatory-stakeholder-network/
    weight: 15
    parent: Home
  - name: "Technical Forum"
    url: ../authors/technical-forum/
    weight: 16
    parent: Home
  - name: Open Music Europe ğŸ‡ªğŸ‡º 
    url: ../authors/openmuse/
    weight: 17
    parent: Home
  - name: "Reprex â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼â¼"
    url: ../authors/reprex/
    weight: 18
    parent: Home
  - name: Join
    url: ../authors/observatory-stakeholder-network/
    weight: 20
    parent: Home
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: EU Open Data Portal
    url: ../data/eu-data-portal/
    weight: 41
    parent: Data
  - name: Europeana
    url: ../data/europeana/
    weight: 42
    parent: Data
  - name: Wikibase
    url: ../data/wikibase/
    weight: 43
    parent: Data
  - name: ğŸ›ï¸ Music Economy
    url: '#pillars'
    weight: 45
    parent: Data
  - name: ğŸ›ï¸ Diversity & Circulation
    url: '#pillars'
    weight: 46
    parent: Data
  - name: ğŸ›ï¸ Music & Society
    url: '#pillars'
    weight: 47
    parent: Data
  - name: ğŸ›ï¸ Music Tech & Innovation
    url: '#pillars'
    weight: 48
    parent: Data
  - name: ğŸ› Sustainability
    weight: 49
    parent: Data
  - name: Services
    url: '#services'
    weight: 50
    identifier: Services
  - name: Applications
    url: 'apps/'
    weight: 51
    parent: Services
  - name: Open Music Software
    url: '#releases'
    weight: 52
    parent: Services
  - name: Code
    url: '/category/r-bloggers/'
    weight: 54
    parent: Services
  - name: Library
    url: '#featured'
    weight: 70
    identifier: Publications
  - name: Featured Publications
    url: '#featured'
    weight: 71
    parent: Publications
  - name: All Publications
    url: '#publications'
    weight: 72
    parent: Publications
  - name: Documentation
    url: https://music.dataobservatory.eu/documentation/
    weight: 74
    parent: Publications
  - name: Open Science Repository
    url: ../data/zenodo/
    weight: 75
    parent: Publications
  - name: Events
    url: '#contact'
    weight: 80
    identifier: Events
  - name: Public talks
    url: '#talks'
    weight: 82
    parent: Events
  - name: Contact
    url: '#contact'
    weight: 95
    identifier: Contact


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
